### ISSUE TITLE
Executing "npm run test" fails - jest not found

### ISSUE THREAD

**Issue by charlesgreen** [simplycubed/firebase-vue-starter#16]
I've configured the package.json in the root folder with lerna and the web and dashboard package.json files however the tests are not able to find the `jest` dependency.

```bash
➜  packages git:(create-dashboard-package) npm run test

> root@1.0.0 test
> lerna run test

lerna notice cli v6.4.1


    ✖  dashboard:test
       > dashboard@0.0.0 test
       > jest

        FAIL   dashboard  __tests__/handler.test.ts
         ● Test suite failed to run

           __tests__/handler.test.ts:10:1 - error TS2304: Cannot find name 'jest'.

           10 jest.mock("../src/config", () => {
              ~~~~

       Failed to collect coverage from /Users/charlesgreen/go/src/github.com/simplycubed/firebase-vue-starter/packages/dashboard/vite.config.ts
       ERROR: Jest worker encountered 3 child process exceptions, exceeding retry limit
       STACK: Error: Jest worker encountered 3 child process exceptions, exceeding retry limit
           at ChildProcessWorker.initialize (/Users/charlesgreen/go/src/github.com/simplycubed/firebase-vue-starter/packages/dashboard/node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:21)
           at ChildProcessWorker._onExit (/Users/charlesgreen/go/src/github.com/simplycubed/firebase-vue-starter/packages/dashboard/node_modules/jest-worker/build/workers/ChildProcessWorker.js:330:12)
           at ChildProcess.emit (node:events:526:28)
           at ChildProcess.emit (node:domain:475:12)
           at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
       Test Suites: 1 failed, 1 total
       Tests:       0 total
       Snapshots:   0 total
       Time:        39.109 s
       Ran all test suites.
....
```

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/1191302/212882543-78abecaa-ac61-4c08-a4fb-5252b25cf94d.png">

**Comment by charlesgreen** [comment]
@anasmuhmd fixed with PR #22
